import 'dart:async';
import 'package:bloc_test/bloc_test.dart';
import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:ln_foot/blocs/network_bloc/network_bloc.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';

// Generate mocks for Connectivity
@GenerateMocks([Connectivity])
import 'network_bloc_test.mocks.dart'; // Will be generated by build_runner

void main() {
  late MockConnectivity mockConnectivity;
  late StreamController<List<ConnectivityResult>> connectivityStreamController;

  setUp(() {
    mockConnectivity = MockConnectivity();
    connectivityStreamController = StreamController<List<ConnectivityResult>>.broadcast();
    
    // Stub the onConnectivityChanged stream
    when(mockConnectivity.onConnectivityChanged)
        .thenAnswer((_) => connectivityStreamController.stream);
    
    // Stub the checkConnectivity method
    when(mockConnectivity.checkConnectivity())
        .thenAnswer((_) async => [ConnectivityResult.wifi]); // Default to online for initial check
  });

  tearDown(() {
    connectivityStreamController.close();
  });

  group('NetworkBloc', () {
    blocTest<NetworkBloc, NetworkState>(
      'emits [NetworkOnline] when initial check is online',
      build: () {
        when(mockConnectivity.checkConnectivity())
            .thenAnswer((_) async => [ConnectivityResult.wifi]);
        return NetworkBloc(connectivity: mockConnectivity);
      },
      expect: () => [isA<NetworkOnline>()],
      verify: (_) {
        verify(mockConnectivity.checkConnectivity()).called(1);
      }
    );

    blocTest<NetworkBloc, NetworkState>(
      'emits [NetworkOffline] when initial check is none',
      build: () {
        when(mockConnectivity.checkConnectivity())
            .thenAnswer((_) async => [ConnectivityResult.none]);
        return NetworkBloc(connectivity: mockConnectivity);
      },
      expect: () => [isA<NetworkOffline>()],
       verify: (_) {
        verify(mockConnectivity.checkConnectivity()).called(1);
      }
    );
    
    blocTest<NetworkBloc, NetworkState>(
      'emits [NetworkOffline] when ConnectivityResult.none is emitted',
      build: () => NetworkBloc(connectivity: mockConnectivity),
      act: (bloc) => connectivityStreamController.add([ConnectivityResult.none]),
      expect: () => [isA<NetworkOnline>(), isA<NetworkOffline>()], // Initial Online, then Offline
    );

    blocTest<NetworkBloc, NetworkState>(
      'emits [NetworkOnline] when ConnectivityResult.wifi is emitted',
      build: () {
         when(mockConnectivity.checkConnectivity())
            .thenAnswer((_) async => [ConnectivityResult.none]); // Start offline
        return NetworkBloc(connectivity: mockConnectivity);
      },
      act: (bloc) => connectivityStreamController.add([ConnectivityResult.wifi]),
      expect: () => [isA<NetworkOffline>(), isA<NetworkOnline>()], // Initial Offline, then Online
    );

    blocTest<NetworkBloc, NetworkState>(
      'emits [NetworkOnline] when ConnectivityResult.mobile is emitted',
      build: () {
         when(mockConnectivity.checkConnectivity())
            .thenAnswer((_) async => [ConnectivityResult.none]); // Start offline
        return NetworkBloc(connectivity: mockConnectivity);
      },
      act: (bloc) => connectivityStreamController.add([ConnectivityResult.mobile]),
      expect: () => [isA<NetworkOffline>(), isA<NetworkOnline>()],
    );
    
    blocTest<NetworkBloc, NetworkState>(
      'emits [NetworkOnline] when ConnectivityResult.ethernet is emitted',
      build: () {
         when(mockConnectivity.checkConnectivity())
            .thenAnswer((_) async => [ConnectivityResult.none]); // Start offline
        return NetworkBloc(connectivity: mockConnectivity);
      },
      act: (bloc) => connectivityStreamController.add([ConnectivityResult.ethernet]),
      expect: () => [isA<NetworkOffline>(), isA<NetworkOnline>()],
    );

    blocTest<NetworkBloc, NetworkState>(
      'emits [NetworkOnline] when ConnectivityResult.vpn is emitted (and other network type is present)',
      build: () {
         when(mockConnectivity.checkConnectivity())
            .thenAnswer((_) async => [ConnectivityResult.none]); // Start offline
        return NetworkBloc(connectivity: mockConnectivity);
      },
      // VPN is often combined with another active connection like WiFi or Mobile.
      // The BLoC logic checks for any of these.
      act: (bloc) => connectivityStreamController.add([ConnectivityResult.vpn, ConnectivityResult.wifi]),
      expect: () => [isA<NetworkOffline>(), isA<NetworkOnline>()],
    );
    
    blocTest<NetworkBloc, NetworkState>(
      'emits [NetworkOnline] when multiple online ConnectivityResults are emitted (e.g., mobile and wifi)',
      build: () {
         when(mockConnectivity.checkConnectivity())
            .thenAnswer((_) async => [ConnectivityResult.none]); // Start offline
        return NetworkBloc(connectivity: mockConnectivity);
      },
      act: (bloc) => connectivityStreamController.add([ConnectivityResult.mobile, ConnectivityResult.wifi]),
      expect: () => [isA<NetworkOffline>(), isA<NetworkOnline>()],
    );

    blocTest<NetworkBloc, NetworkState>(
      'emits [NetworkOffline] when ConnectivityResult.bluetooth is emitted (and no other online network type)',
      build: () => NetworkBloc(connectivity: mockConnectivity),
      act: (bloc) => connectivityStreamController.add([ConnectivityResult.bluetooth]),
      // Initial check is wifi (online), then bluetooth is emitted (offline by current BLoC logic)
      expect: () => [isA<NetworkOnline>(), isA<NetworkOffline>()],
    );
    
    blocTest<NetworkBloc, NetworkState>(
      'emits [NetworkOffline] when ConnectivityResult.other is emitted (and no other online network type)',
      build: () => NetworkBloc(connectivity: mockConnectivity),
      // Initial check is wifi (online), then 'other' is emitted (offline by current BLoC logic)
      act: (bloc) => connectivityStreamController.add([ConnectivityResult.other]),
      expect: () => [isA<NetworkOnline>(), isA<NetworkOffline>()],
    );

    test('closes the connectivity subscription when bloc is closed', () async {
      // Build the bloc
      final bloc = NetworkBloc(connectivity: mockConnectivity);
      // Ensure the stream is listened to
      expect(connectivityStreamController.hasListener, isTrue);
      
      // Close the bloc
      await bloc.close();
      
      // Verify that the subscription is cancelled
      // For broadcast streams, hasListener might still be true if other listeners exist.
      // A more direct way is to check if the subscription itself was cancelled,
      // but bloc_test doesn't easily expose this.
      // However, the BLoC's close method calls _connectivitySubscription?.cancel().
      // We can infer this by trying to add an event and seeing if the BLoC reacts (it shouldn't).
      // Or, if we had access to the StreamSubscription, we could check its `isPaused` or state.
      // For this test, we assume the internal cancel works as intended if close() is called.
      // This is more of an integration aspect of the BLoC's own implementation.
      // A simple check: after closing, the bloc should not emit new states if events are pushed to the controller.
      connectivityStreamController.add([ConnectivityResult.none]);
      await Future.delayed(Duration.zero); // Allow microtasks to complete
      // No new expect here as the bloc is closed.
      // This test primarily ensures close() can be called.
      // Verifying cancel directly is hard without exposing the subscription.
    });
  });
}
